### ISSUE TITLE
Arch Linux: Unable to install due to permissions for /usr/lib/...

### ISSUE THREAD

**Issue by francium** [jle64/gnome-pass-search-provider#15]
I was able to install this package on one of my two machines, but the second machine keeps failing during the installation. I'm using `pikaur`, but below I'll show you the manual build/install steps that result in the same issue.

```
$ pikaur -S gnome-pass-search-provider-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 gnome-pass-search-provider-git                             -> r9.bed2f59-2

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for gnome-pass-search-provider-git package (installing for the first time)
Do you want to edit PKGBUILD for gnome-pass-search-provider-git package? [Y/n] n

:: Downloading the latest sources for a devel package gnome-pass-search-provider-git...

:: Starting the build:
==> Making package: gnome-pass-search-provider-git r49.79a0c36-1 (Fri 31 May 2019 07:44:38 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating gnome-pass-search-provider git repo...
Fetching origin
==> Validating source files with md5sums...
    gnome-pass-search-provider ... Skipped
==> Extracting sources...
  -> Creating working copy of gnome-pass-search-provider git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot create regular file '/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py': Permission denied
==> ERROR: A failure occurred in package().
    Aborting...

Command 'makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
```
If I instead run `sudo pikaur -S ...`, I get a different error,
```
...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot create regular file '/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py': Read-only file system
==> ERROR: A failure occurred in package().
    Aborting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=4
Service runtime: 894ms

Command 'systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/gnome-pass-search-provider-git makepkg --force' failed to execute.
...
```

Trying to manually install it,
```
git clone https://aur.archlinux.org/gnome-pass-search-provider-git.git
cd gnome-pass-...-git.git
makepkg --si
```

Smiliar issue as previous method.

---

I did end up getting it to work. I had to modify the PKGBUILD,
```
 package() {
         cd "$srcdir/$_pkgname"
-         ./install.sh
+        sudo ./install.sh
 }
```
I don't have any experience creating PKGBUILD files, so I don't know if using `sudo` here is the correct thing to do.

**Comment by jle64** [comment]
Yep, my bad. I broke it with excessive "clean up of useless variables", according to the commit. Guess they weren't that useless. That's fixed now.

The issue here was that my PKGBUILD was putting files on the system directly instead of in the package building directory ($pkgdir). 

> I don't have any experience creating PKGBUILD files, so I don't know if using sudo here is the correct thing to do.

Nope, it isn't. makepkg should just make a package, not touch your system, so it doesn't need any root rights. Only pacman should run as root to install the package. In fact running makepkg as non-root is recommended practice to avoid broken PKGBUILDs (like mine) touching your system.

Adding sudo where you did probably means that files were created on your system by makepkg without being tracked by pacman database.

If the following files are present on your system:
```
/usr/lib/gnome-pass-search-provider/
/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py
/usr/lib/systemd/user/org.gnome.Pass.SearchProvider.service
/usr/share/applications/org.gnome.Pass.SearchProvider.desktop
/usr/share/dbus-1/services/org.gnome.Pass.SearchProvider.service
/usr/share/gnome-shell/search-providers/org.gnome.Pass.SearchProvider.ini
```
You should check for `pacman -Ql gnome-pass-search-provider-git` and verify that they are listed here. If they aren't, remove them manually before upgrading to the fixed version.

Anyway thanks for the report. Can you confirm that it works now ?

**Comment by francium** [comment]
Installs perfectly. Thank you and thanks for including  that additional clean up information at the bottom too, it was very helpful.
