### ISSUE TITLE
Writing an Ebuild for Gentoo

### ISSUE THREAD

**Issue by r7l** [jle64/gnome-pass-search-provider#22]
Hello,

i was attempting to write an Ebuild for Gentoo for this extension. I've closely followed the install.sh but i wasn't using it directly. So far, all the files are in their expected places.

Somehow i am still getting this error:

```gnome-shell[1283]: Received error from DBus search provider org.gnome.Pass.SearchProvider.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Pass.SearchProvider was not provided by any .service files```

The file itself is there:

`-rw-r--r-- 1 root root 198 14. Dez 16:06 /usr/lib/systemd/user/org.gnome.Pass.SearchProvider.service`

Is there anything i've missed?

Running Gnome Shell 3.32

**Comment by jle64** [comment]
Hey,

> i was attempting to write an Ebuild for Gentoo for this extension.

Cool ! Ping me when it works so I can mention it in the README.

> Is there anything i've missed?

If all the files are here I don't think so.

Have you closed/reopened your session after installation ?

Are you sure systemd is handling dbus user services activation on your system ? I ask because I'm not sure it's the default on Gentoo even if you're using systemd. If the `dbus-daemon` running under your user has `--systemd-activation` in its options or if you have `dbus-broker` instead of `dbus-daemon` that should mean it's systemd that starts stuff, otherwise it's dbus itself. Both are fine but that changes which file is used to activate the service.

 _ If systemd handles starting dbus stuff, does a `systemctl --user status org.gnome.Pass.SearchProvider.service` sees the service ? It should show as `Loaded: loaded`. If it doesn't, does a `systemctl --user daemon-reload` changes anything` ?

 _ If dbus handles starting stuff by itself, then the file that matters instead is `/usr/share/dbus-1/services/org.gnome.Pass.SearchProvider.service`. Can you check than the file is here ?

**Comment by r7l** [comment]
Thanks for your response. I'll notify you once i am done with it but it might take a little as my overlay (community package repository) is not yet included in the Gentoo overlay system. I am planning to do so.

For now with this Ebuild i am stuck with systemd or something. I have to admit that i've just recently started using systemd as it might be the better option with Gnome and it wasn't (and still isn't) a dependency of Gentoo. I am otherwise using XFCE with OpenRC.

When running `systemctl --user status org.gnome.Pass.SearchProvider.service` i'll get this as a response:

```
systemctl --user status org.gnome.Pass.SearchProvider.service
● org.gnome.Pass.SearchProvider.service - Pass search provider for GNOME Shell daemon
   Loaded: loaded (/usr/lib/systemd/user/org.gnome.Pass.SearchProvider.service; static; vendor preset: enabled)
   Active: inactive (dead)
```

So it seems to be there and working with systemd as `/usr/share/dbus-1` is only existing on non-systemd systems for me. I am not sure what this `inactive (dead)` actually means. I've tried `systemctl --user daemon-reload` but that doesn't change anything. Would shutting down and restarting the system close a Gnome session? I would expect so as that's what i did over night.

**Comment by jle64** [comment]
The `inactive` part is normal (it should only become active on-demand) but the `(dead)` part seems to indicate that it was started and then died, which is not normal (once started it should stay on).

Can you execute the gnome-pass-search-provider.py script manually from a terminal and see if it runs fine ? And if it runs fine can you try searching for a password from gnome-shell to see if that works or if that generates an exception ?

**Comment by r7l** [comment]
It does work once i run the `gnome-pass-search-provider.py` in a terminal and it stops the second i am canceling it.

**Comment by r7l** [comment]
I am still trying to figure out how this works as i am new to Gnome and systemd. Using the search should trigger this Python script and start the search. Once done, it stops and shouldn't be running otherwise? I can't see any reference on the Readme that would give a clue about starting the Python script manually.

**Comment by jle64** [comment]
>  I can't see any reference on the Readme that would give a clue about starting the Python script manually.

Yeah because you shouldn't have to, that was just to know if the script itself worked. If it didn't and exited that would have explained why systemd said it was dead.

> I am still trying to figure out how this works as i am new to Gnome and systemd. Using the search should trigger this Python script and start the search. Once done, it stops and shouldn't be running otherwise?

Using the search makes gnome-shell call the dbus api which should make systemd start the script. It stays on after being started however.

**Comment by jle64** [comment]
Closing for now, feel free to re-open if needed.
