### ISSUE TITLE
Environment variable loading

### ISSUE THREAD

**Issue by demolg** [jle64/gnome-pass-search-provider#26]
I'd like to set a environment variable in `.bashrc`.
```
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass
```
Then this search provider doesn't work. Please fix it.

**Comment by jle64** [comment]
As explained in the README, environment variables need to be set in a way that they propagate to the gnome-pass-search-provider.py process.

Since `~/.bashrc` is not sourced by GNOME at startup, it won't work, you need instead to set them in `~/.pam_environment`, `~/.profile` or something else depending on your OS, then restart the gnome session and verify that they propagate to the gnome-pass-search-provider.py process with, for example, `ps auxeww | grep [g]nome-pass-search-provider.py`.

**Comment by demolg** [comment]
Thank you!
